apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-node-doctor
bases:
  - ../../base
patchesStrategicMerge:
  - configmap.yaml
  - advancedcronjob.yaml
configMapGenerator:
  - name: k8s-node-doctor-config
    behavior: merge